apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ejbca

labels:
  - includeSelectors: true
    pairs:
      app: ejbca

resources:
  - deploy.yaml
  - service.yaml
  - ingress.yaml

