apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ejbca

labels:
  - includeSelectors: true
    pairs:
      app: ejbca

resources:
  - deploy.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: ghcr.io/crisfint1425/ejbca
    newName: ghcr.io/crisfint1425/ejbca
    newTag: "firmada1"   # valor inicial — luego Argo Image Updater pondrá digest

