apiVersion: v1
kind: Service
metadata:
  name: ejbca-service
  namespace: ejbca
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
  labels:
    app: ejbca
spec:
  type: LoadBalancer
  selector:
    app: ejbca
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8443

